spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DamienLinux/tpmicroservicesMIAGE.git
          username: DamienLinux
          password: Avette@9391
          clone-on-start: true